site_name: Our Maths Solutions
nav:
    - Home: index.md
    - Integral Topic Accessment:
      - Pure Year 1:
        - Surds and Indices: './Pure Year 1/Surds and Indices/test.md'
        - Quadratic Functions: './Pure Year 1/Quadratic Functions/test.md'
        - Equations and Inequalities: './Pure Year 1/Equations and Inequalities/test.md'
        - Coordinate Geometry: './Pure Year 1/Coordinate Geometry/test.md'
        - Trigonometry: './Pure Year 1/Trigonometry/test.md'
        - Polynomials: './Pure Year 1/Polynomials/test.md'
        - Graphs and Transformations: './Pure Year 1/Graphs and Transformations/test.md'
        - Binomial Expansion: './Pure Year 1/Binomial Expansion/test.md'
        - Differentiation: './Pure Year 1/Differentiation/test.md'
        - Integration: './Pure Year 1/Integration/test.md'
        - Vectors: './Pure Year 1/Vectors/test.md'
        - Exponentials and Logarithms: './Pure Year 1/Exponentials and Logarithms/test.md'
      - Mechanics Year 1:
        - Kinematics: './Mechanics Year 1/Kinematics/test.md'
        - Forces and Newton's Laws: './Mechanics Year 1/Forces and Newtons Laws/test.md'
        - Variable Acceleration: './Mechanics Year 1/Variable Acceleration/test.md'
      - Statistics Year 1:
        - Collecting and Interpretation Data: './Statistics Year 1/Collecting and Interpreting Data/test.md'
        - Probability: './Statistics Year 1/Probability/test.md'
        - Binomial Distributions: './Statistics Year 1/Binomial Distributions/test.md'
        - Statistical Hypothesis Testing: './Statistics Year 1/Statistical Hypothesis Testing/test.md'
      - Pure Year 2:
        - Proof: './Pure Year 2/Proof/test.md'
        - Trigonometry: './Pure Year 2/Trigonometry/test.md'
        - Sequences and Series: './Pure Year 2/Sequences and Series/test.md'
        - Functions: './Pure Year 2/Functions/test.md'
        - Differentiation: './Pure Year 2/Differentiation/test.md'
        - Trigonometric Functions: './Pure Year 2/Trigonometric Functions/test.md'
        - Trigonometric Identities: './Pure Year 2/Trigonometric Identities/test.md'
        - Algebra: './Pure Year 2/Algebra/test.md'
        - Further differentiation: './Pure Year 2/Further Differentiation/test.md'
        - Integration: './Pure Year 2/Integration/test.md'
        - Parametric Equations: './Pure Year 2/Parametric Equations/test.md'
        - Vectors: './Pure Year 2/Vectors/test.md'
        - Differentiation Equations: './Pure Year 2/Differentiation Equations/test.md'
        - Numerical Methods: './Pure Year 2/Numerical Methods/test.md'
      - Mechanics Year 2:
        - Kinematics: './Mechanics Year 2/Kinematics/test.md'
        - Forces and Motion: './Mechanics Year 2/Forces and Motion/test.md'
        - Moments of Forces: './Mechanics Year 2/Moments of Forces/test.md'
        - Projectiles: './Mechanics Year 2/Projectiles/test.md'
        - Model for Friction: './Mechanics Year 2/Model for Friction/test.md'
      - Statistics Year 2:
        - Probability: './Statistics Year 2/Probability/test.md'
        - Statistical Distributions: './Statistics Year 2/Statistical Distributions/test.md'
        - Statistical Hypothesis Testing: './Statistics Year 2/Statistical Hypothesis Testing/test.md'
    # - Homeworks:
    #   - Pure: './Homeworks/pure.md'
    #   - Mechanics: './Homeworks/mechanics.md'
    #   - Statistics: './Homeworks/statistics.md'
    # - Past Papers:
    #   - 2024: './Past Papers/test.md'
    # - Draft: 
    #    - Draft: './Draft/draft.md'

theme: material

extra_css:
  - stylesheets/extra.css