<div style="font-size: 20px;">

<p align="center">
<img src="/images/otter.jpg" alt="drawing" width="500"/>
</p>

<br><br>

1. **Differentiate the following functions.**

(a) $y=\sin ^{2} x$

<br>

+++ <span style="color:blue">Hint</span>

<hr style="border:1px solid red" >

<br>
<br>

\begin{equation}
\begin{aligned}
\frac{d\left(\sin ^2 x\right)}{d x} & =\frac{d \sin x }  {d x} \cdot 2 \cdot \sin x \\
&=2 \cdot \sin x \cdot \cos x \\
&=2 \sin (2 x)&&
\end{aligned}
\end{equation}

<br>

In equation (1), we apply chain rule That is so funny! :joy:
<span style="color:red">some *red* text</span>.

<br>

\begin{equation}
\begin{aligned}
&y=\sin x \Rightarrow \frac{d y}{d x}=\cos x \\
&y=x^2 \Rightarrow \frac{d\left(x^2\right)}{d x}=2 x
\end{aligned}
\end{equation}

<hr style="border:1px solid red" >

+++

<br>

+++ <span style="color:green">Solutions</span>

<hr style="border:1px solid red" >

<br>
<br>

\begin{equation}
\begin{aligned}
\frac{d\left(\sin ^2 x\right)}{d x} & =\frac{d \sin x }  {d x} \cdot 2 \cdot \sin x \\
&=2 \cdot \sin x \cdot \cos x \\
&=2 \sin (2 x)&&
\end{aligned}
\end{equation}

<br>
<br>

\begin{equation}
\begin{aligned}
&y=\sin x \Rightarrow \frac{d y}{d x}=\cos x \\
&y=x^2 \Rightarrow \frac{d\left(x^2\right)}{d x}=2 x
\end{aligned}
\end{equation}

<hr style="border:1px solid red" >

+++


<br>

(b) $y=x^{2} \cos x$

<br>

\((c)\) $y=\frac{x}{\tan 2 x}$

<br>

(d) $y=a^{2 x^{2}}$ where $a$ is a positive constant greater than 1 .

<br>


<hr style="border:1px solid grey" >


2.
(a) Show from first principles that for the curve $y=\sin x$, where $x$ is in radians,

$$
\frac{\mathrm{d} y}{\mathrm{~d} x}=\cos x
$$

You may use the formula for $\sin (A \pm B)$ without proof and assume that as $h \rightarrow 0$,
$$
\frac{\cos h-1}{h} \rightarrow 0 \text { and } \frac{\sin h}{h} \rightarrow 1
$$

<br>

(b) Identify where in the proof this assumption that $x$ is in radians is needed.

<br>

<hr style="border:1px solid grey" >

3.
(a) Find an expression in terms of $x$ and $y$ for the gradient of the curve
$$
x^{2}+k x y+4 y^{2}=48
$$

<br>

(b) The diagram shows the curve where $k=2$.

<p align="center">
<img src="https://cdn.mathpix.com/cropped/2025_10_05_85d57a8dd1c2922b6613g-1.jpg?height=410&width=566&top_left_y=1364&top_left_x=505" alt="drawing" width="300"/>
</p>

<br>

Find the values of $y$ for which the tangent to the curve is vertical.

\((c)\) Explain what happens to the gradient when $k=4$.

<br>

<hr style="border:1px solid grey" >

4. **In this question you must show detailed reasoning**

Show that the curve $y=x-\ln x$ has one turning point only, and give the coordinates of this point.

<br>

<hr style="border:1px solid grey" >

5. **In this question you must show detailed reasoning**

A curve has $y=\mathrm{e}^{2 x} \cos x$

(a) Show that the turning points of the curve occur at the points for which $\tan x=2$.

<br>

(b) Find the equation of the normal to the curve at the point for which $x=0$.

</div>